pipeline{
    agent any

    parameters{
        string(name: 'APP_NAME', defaultValue: 'Davita', description: "Please enter the name of your app")
        choice(name: 'ENVIRONMENT', choices: ["dev", "staging", "prod"], description: "Please select the env you would like to deploy to")
        booleanParam(name: 'RUN_TESTS', defaultValue: false, description: "Please select if you want to run tests")
    }

    environment {
        DEPLOYER =  "Hello Abhishek Alimchandani, hope this works"
    }

    stages{
        stage('Intro'){
            steps{
                echo "${env.DEPLOYER} on the ${params.ENVIRONMENT} environment"
            }
        }
        // Here instead of this we can use the when{} block in which the key difference it helps us skip this step entirelly when it is not needed
        // stage('Run Tests'){
        //     steps{
        //         script{
        //             if(params.RUN_TESTS == true){
        //                 echo "All the tests ran successfully"
        //             }else {
        //                 echo "All tests cases were skipped  "
        //             }
        //         }
        //     }
        // }

        stage('Run Tests'){
            when{
                expression {return params.RUN_TESTS}
            }

            steps{
                echo "Running tests before deploying it"
            }
        }

        stage('Deploy'){
            steps{
                script{
                    if (params.ENVIRONMENT == 'dev') {
                        echo "Deploying it to the dev env"
                    } else if (params.ENVIRONMENT == 'staging') {
                        echo "Deploying it to the staging env"
                    } else {
                        echo "Deploying it to the prod env"
                    }
                }
            }
        }
    }
}