@Library('schedule-lib@main') _ 

pipeline{
    agent any 

    parameters{
        string(name: "USERNAME",defaultValue: "Abhishek Alimchandani", description: "Please enter your name here");
        choice(name: "DEPLOY_ENV", choices: ['dev','main','test'], description: "Please select the env you would like to deploy to")
    }

    stages{
        stage('Greet Info'){
            steps{
                greetUser(this)
            }
        }
    }
}