@Library('schedule-lib@main') _ 

pipeline{
    agent any 

    tools{
        nodejs 'Node23'
    }

    parameters{
        string(name: "USERNAME",defaultValue: "Abhishek Alimchandani", description: "Please enter your name here");
        choice(name: "DEPLOY_ENV", choices: ['dev','main','test'], description: "Please select the env you would like to deploy to")
    }

    environment{
        APP_DIR = "12-Scheduled-Build-Pipeline"
    }

    stages{
        stage('Greet Info'){
            steps{
                greetUser(this)
            }
        }

        stage('Install Build'){
            steps{
                npmInstallAndBuild(this)
            }
        }

        //stage('Archive Artifacts')
    }
}