pipeline {
    agent any

    stages{
        stage('Greeting'){
            steps{
                echo "Hello I am Abhishek Alimchandani !! "
            }
        }

        stage('Build'){
            steps{
                sh 'npm run build'
            }
        }

        stage('Test'){
            when {
                any of{
                    branch 'dev'
                    branch 'main'
                }
            }

            steps{
                sh 'npm run test'
            }
        }

        stage('Deploy'){
            when{
                expression {env.BRANCH_NAME == 'main'}
            }

            steps{
                echo "Deploying on main branch"
                input message: "Are you sure you want to deploy on the main branch", ok: "Yes, go ahead!"
            }
        }
    }

    post {
    success {
        echo "✅ Build for ${env.BRANCH_NAME} succeeded"
    }
    failure {
        echo "❌ Build failed on ${env.BRANCH_NAME}"
    }
}
}