pipeline {
    agent any

    tools{
        nodejs 'Node23'
    }

    environment{
        APP_DIR = '09-Multibranch-Jenkins-Pipeline'
    }

    stages{
        stage('Greeting'){
            steps{
                echo "Hello I am Abhishek Alimchandani !! "
            }
        }

        stage('Build'){
            steps{
                dir("${env.APP_DIR}"){
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        stage('Test'){
            when {
                anyOf{
                    branch 'dev'
                    branch 'main'
                }
            }

            steps{
                dir("${APP_DIR}"){
                    sh 'npm run test'
                }
            }
        }

        stage('Deploy'){
            when{
                expression {env.BRANCH_NAME == 'main'}
            }

            steps{
                echo "Deploying on main branch"
                input message: "Are you sure you want to deploy on the main branch", ok: "Yes, go ahead!"
            }
        }
    }

    post {
    success {
        echo "✅ Build for ${env.BRANCH_NAME} succeeded"
    }
    failure {
        echo "❌ Build failed on ${env.BRANCH_NAME}"
    }
}
}