pipeline{
    agent any

    stages{
        stage('Hello-World'){
            steps{
                echo "👋 Hello from Jenkins Pipeline!"
            }
        }

        stage('Info'){
            steps{
                sh 'whoami'
                sh 'pwd'
            }
        }
    }
}