pipeline{
    agent any

    stages{
        stage('Hello-World'){
            steps{
                echo "👋 Hello from Jenkins Pipeline!"
                sh 'node hello.js'
            }
        }
    }
}