pipeline{
    agent any

    tools {
    nodejs 'node23.10.0'
    }

    stages{
        stage('Hello-World'){
            steps{
                echo "👋 Hello from Jenkins Pipeline!"
            }
        }
    }
}