@Library('local-lib@main') _ 

pipeline {
    agent any 

    stages {
        stage('Greet') {
            steps {
                greetHello()
            }
        }

        stage('Install and Build'){
            steps{
                npmInstallAndBuild()
            }
        }
    }
}
