pipeline {
    agent any

    tools {
        nodejs 'Node23'
    }

    environment {
        APP_DIR = '06-Archive-Artifacts-Pipeline'
    }

    stages {
        stage('Install All Packages') {
            steps {
                dir("${APP_DIR}") {
                    sh 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                dir("${APP_DIR}") {
                    sh 'npm run build'
                }
            }
        }

        stage('Test') {
            steps {
                dir("${APP_DIR}") {
                    sh 'npm run test'
                }
            }
        }

        stage('Archive Artifacts') {
            steps {
                dir("${APP_DIR}") {
                    archiveArtifacts artifacts: 'dist/**', fingerprint: true
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully! ✅'
        }
        failure {
            echo 'Pipeline failed. Check the logs. ❌'
        }
    }
}
