pipeline{
    agent any

    stages{
        stage('Install All Packages'){
            steps{
                sh 'npm install'
            }
        }

        stage('Build'){
            steps{
                sh 'npm run build'
            }
        }

        stage('Test'){
            steps{
                sh 'npm run test'
            }
        }

        stage('Archive Artifacts'){
            steps{
                archiveArtifacts artifacts: 'dist/**', fingerprint: true
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check the logs.'
        }
    }
}