pipeline{
    agent any

    stages{
        stage("Greet"){
            steps{
                echo "Hello here we learn how to send Gmail Notifications from ${env.USER_NAME}"
            }
        }
    }

    post{
        success{
            mail to:'abhishekalimchandani1624@gmail.com',
            subject: "✅ Jenkins Build successfull - ${env.JOB_NAME}  #${env.BUILD_NUMBER}",
            body: "Good news! The build completed successfully .\n\n Check Jenkins: ${env.BUILD_URL}"
        }
        failure{
            mail to:'abhishekalimchandani1624@gmail.com',
            subject: "❌ Jenkins Build Failed - ${env.JOB_NAME}  #${env.BUILD_NUMBER}",
            body: "Something went wrong. Please check the logs.\n\nJob: ${env.JOB_NAME}\nBuild: ${env.BUILD_URL}"
        }    
    }
}