pipeline{
    agent any

    stages{
        stage ('Run All Tests'){
            parallel{
                stage('Unit Tests'){
                    steps{
                        echo "Running all the unit tests"
                    }
                }
                stage('API Tests'){
                    steps{
                        echo "Running all API tests"
                        sleep(3)
                    }
                }
                stage('UI Tests'){
                    steps{
                        echo "Running all UI Tests"
                    }
                }
            }
        }
    }

    post{
        success {
            echo '✅ Pipeline succeeded'
        }

        failure {
            echo '❌ Pipeline failed!'
        }
    }
}

//Other type of common post conditons
/*
always – runs no matter what (success or failure)
success – only runs if the pipeline (or stage) succeeded
failure – only runs if it failed
unstable – runs if marked unstable (e.g., test failures)
changed – runs only if the current pipeline result is different from the previous one
*/
