pipeline {
    agent any

    stages{
        stage('Build App'){
            steps{
                echo "Building the application..."
            }
        }

        stage('Run Tests'){
            steps{
                echo "Running unit and integration tests..."
            }
        }

        //So here if we abort it will not go to the next step only
        stage('Approval Gate'){
            steps{
                input message: "QA Team, do you approve this deployment to production", ok: "Yes, proceed"
            }
        }

        //This is how we can see who clicked the approve also
        // stage('Re confirmation') {
        //     steps{
        //         script{
        //             def approver = input(
        //             message: "Are you sure you want to continue",
        //             ok: "Yess"
        //              )
        //             echo "Approved by ${approver}"
        //         }
        //     }
        // }

        stage('Deploy to Production'){
            steps{
                echo "Deploying application to production.."
            }
        }
    }

    post {
        always{
            echo "🧹 Cleaning the workspace.."
        }

        success {
            echo "Pipeline succeeded 🎉"
        }

        failure {
            echo "Pipeline failed ❌"
        }
    }
}